### ISSUE TITLE
Issue with Podfile

### ISSUE THREAD

**Issue by kashiftriffort** [liman123/DebugMan#1]
When I try to install Podfile, it's showing warning.. Unable to find a pod with name, author, summary, or description matching `DebugMan. Please help me in this.

**Comment by liman123** [comment]
run `pod setup` or `pod repo update` first, enjoy~

**Comment by kashiftriffort** [comment]
Hi,
I have followed your steps, it didn't work, even I tried to find pod search DebugMan, it still showing Unable to find a pod with name, author, summary, or description matching `DebugMan.

**Comment by kashiftriffort** [comment]
Sorry, it worked, I tried on different project.

**Comment by liman123** [comment]
![screen shot 2018-01-19 at 5 38 32 pm](https://user-images.githubusercontent.com/6781027/35144573-dfe5d6c4-fd3f-11e7-9235-1b7849908410.png)

**Comment by anysome** [comment]
Now I can't find 4.4.4 now. Would you please keep history version?

**Comment by liman123** [comment]
Sorry! I accidentally deleted the history pods version. 
I  just updated the new version. You can just use `pod 'DebugMan', :configurations => ['Debug']`,  run `pod update DebugMan`. this can help you to use the latest version. Enjoy~
![screen shot 2018-01-26 at 10 20 50 am](https://user-images.githubusercontent.com/6781027/35422336-19cac15e-0283-11e8-96b4-d6d7dc5ea226.png)

**Comment by liman123** [comment]
If you need more help, just let me know.
