### ISSUE TITLE
Filter in DebugMan

### ISSUE THREAD

**Issue by hendyevan** [liman123/DebugMan#2]
Hi, im using this library and running in iphone 7, but i can not filter my post because the text field show in nav bar.
![img_0707](https://user-images.githubusercontent.com/982972/35145846-d96f8690-fd3b-11e7-904e-1b4b24221e85.jpg)

**Comment by hendyevan** [comment]
Im using real device. My iOS version is 11.2.1

**Comment by liman123** [comment]
I guess you may changed your navigation bar Global somewhere in your project. Next new version release I will fix this. maybe tomorrow

**Comment by hendyevan** [comment]
Im not changing navigation bar for global, only for each viewcontroller. Ok, please inform if you release next version and i will update it.

**Comment by liman123** [comment]
I have found out the reason...tomorrow I will fix it and inform you. @hendyevan 

    UINavigationBar.appearance().setBackgroundImage(UIImage(), for: .default)
    UINavigationBar.appearance().shadowImage = UIImage()
    UINavigationBar.appearance().backgroundColor = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.0)
    UINavigationBar.appearance().isTranslucent = true

![snip20180119_2](https://user-images.githubusercontent.com/6781027/35147898-40330cb2-fd4b-11e7-9a35-32314e382de7.png)

**Comment by hendyevan** [comment]
Awesome! Thank you very much for your support.

**Comment by liman123** [comment]
if you can not wait tomorrow, you can temporarily add this one line code `navigationBar.isTranslucent = false` in `Pods/DebugMan/LogNavigationViewController.swift`
tomorrow I will release new version. Enjoy~ @hendyevan 

![snip20180119_3](https://user-images.githubusercontent.com/6781027/35148330-b273f6d2-fd4c-11e7-8318-69c8b6aeabb3.png)

**Comment by liman123** [comment]
This bug has been fixed.
