### ISSUE TITLE
unable to archive with DebugMan

### ISSUE THREAD

**Issue by askari01** [liman123/DebugMan#3]
unable to archive with DebugMan

**Comment by liman123** [comment]
sorry, I do not understand your problem. can you description more? @askari01

**Comment by liman123** [comment]
If you import DebugMan with cocoapods: (I commend import DebugMan only in Xcode debug mode)

    pod 'DebugMan', :configurations => ['Debug'] 

you should import DebugMan like this:

     #if DEBUG
           import DebugMan
     #endif

**Comment by liman123** [comment]
If you need more help, just let me know.
