### ISSUE TITLE
Logging isn't working

### ISSUE THREAD

**Issue by jcramer** [liman123/DebugMan#6]
I implemented the Swift print<T> function as described in the readme but the logging isn't coming into the debug man logger.  Using swift 4.

**Comment by liman123** [comment]
Have you tried my Swift Example? If not, just `git clone https://github.com/liman123/DebugMan.git`, and then run my Swift Example. I am sure my example works well.
If you need more help, just let me know~

**Comment by jcramer** [comment]
thanks
